
NAME = Zombie
HEADER = Zombie.hpp
CXXFLAGS =  -Wall -Wextra -Werror -std=c++98

CXX = c++

SRCS = main.cpp\
	newZombie.cpp\
	randomChump.cpp\
	Zombie.cpp

OBJS = main.o\
	newZombie.o\
	randomChump.o\
	Zombie.o

all: $(NAME)

$(NAME): $(OBJS) $(HEADER)
	$(CXX) $(CFLAGS) $(OBJS) -o $(NAME)
clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

PHONY: all clean fclean re
